name: React CI

on:
  push:
    branches:
      - "react-actions"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1
      - run: cd packages/client && npm install
      - run: npm run build
